name: smol_crudclient_felipe
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  formz: ^0.4.1
  equatable: ^2.0.5
  intl: ^0.18.0
  dio: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
      - family: CustomIcons
        fonts:
          - asset: assets/fonts/icon/Custom-Icon.ttf
      - family: Inter
        fonts:
          - asset: assets/fonts/inter/Inter-Regular.ttf
            weight: 400
            style: normal
          - asset: assets/fonts/inter/Inter-Bold.ttf
            weight: 700
            style: normal